# Generated by Django 3.0.2 on 2020-01-11 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('title_cn', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('content_cn', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-create_at',),
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('info', models.CharField(max_length=40)),
                ('info_cn', models.CharField(max_length=40)),
                ('status', models.BooleanField()),
                ('payment', models.IntegerField(choices=[(0, 'alipay face to face'), (1, 'aff from user'), (5, 'buy service')], default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('trade_no', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-create_at',),
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('name_cn', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=40)),
                ('description_cn', models.CharField(max_length=40)),
                ('host', models.CharField(max_length=40)),
                ('mode', models.IntegerField(choices=[(0, 'Shadowsocks'), (1, 'V2ray')], default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-create_at',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('title_cn', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=300)),
                ('description_cn', models.CharField(max_length=300)),
                ('data_per_month', models.IntegerField(default=0)),
                ('days', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('traffic_up', models.BigIntegerField(default=0, verbose_name='Upload traffic')),
                ('traffic_down', models.BigIntegerField(default=0, verbose_name='download Traffic')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('remark', models.CharField(max_length=40)),
                ('port', models.CharField(default='', max_length=5)),
                ('uuid', models.CharField(max_length=36)),
                ('password', models.CharField(max_length=40)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('reset_at', models.DateTimeField()),
                ('expired_at', models.DateTimeField()),
                ('method', models.CharField(default='rc4-md5', max_length=40)),
                ('data_per_month', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.IntegerField(choices=[(0, 'disable'), (1, 'enable')], default=0)),
                ('traffic_up', models.BigIntegerField(default=0)),
                ('traffic_down', models.BigIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Service')),
            ],
            options={
                'ordering': ('-create_at',),
            },
        ),
    ]
