# Generated by Django 2.2.9 on 2020-02-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_codepay'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlipayOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('info', models.CharField(max_length=40)),
                ('status', models.IntegerField(choices=[(0, '未支付'), (1, '支付成功')], default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('trade_no', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-create_at',),
            },
        ),
        migrations.RemoveField(
            model_name='bill',
            name='trade_no',
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment',
            field=models.IntegerField(choices=[(0, '支付宝'), (1, '邀请用户奖励'), (2, '充值码充值'), (5, '购买服务')], default=0),
        ),
    ]
