# Generated by Django 2.2.9 on 2020-02-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200211_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='trade_no',
            field=models.CharField(default='code_1', max_length=100),
            preserve_default=False,
        ),
    ]
